/*
 * Engine: MySQL
 * Version: 0.0.1
 * Description: Initial database structure
 */

/*
-- create schema
CREATE SCHEMA sbgql;

-- use schema
USE sbgql;

-- Create user 
create user 'sbgql'@'localhost' identified by 'sbgql';

-- Grant privileges to user
grant all privileges on *.* to 'sbgql'@'localhost' with grant option;
 */

--
-- Table structure for table `person`
--

create table books (id bigint generated by default as identity, created_date timestamp, last_modified_date timestamp, title varchar(255) not null, person_id bigint, primary key (id))


--
-- Table structure for table `books`
--

create table person (id bigint generated by default as identity, created_date timestamp, last_modified_date timestamp, age integer, date_of_birth timestamp, email varchar(255) not null, is_adult boolean not null, mobile_number varchar(255), name varchar(255) not null, primary key (id))

--
-- Alter Tables
--

alter table person drop constraint if exists UK_fwmwi44u55bo4rvwsv0cln012
alter table person add constraint UK_fwmwi44u55bo4rvwsv0cln012 unique (email)
alter table books add constraint FK5w75tx731o2t3abhgesnobgih foreign key (person_id) references person

/*
 * Data
 */

INSERT INTO `person` (`age`,`email`,`mobile_number`,`name`,`is_adult`,`date_of_birth`) VALUES (30,'example1@domain1.com','10987654321','jane doe',1,'1989-08-16');
INSERT INTO `person` (`age`,`email`,`mobile_number`,`name`,`is_adult`,`date_of_birth`) VALUES (28,'example2@domain2.com','10987654322','John doe',0,'1992-09-15');

/*
 * Data
 */

INSERT INTO `books` (`title`,`person_id`) VALUES ('book1',1);
INSERT INTO `books` (`title`,`person_id`) VALUES ('book2',1);